name: TER

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        run: sudo update-alternatives --set php /usr/bin/php7.1

      - name: Install requirements
        run: composer global require --dev helhum/ter-client dev-master

      - name: Cleanup before we upload
        run: git reset --hard HEAD && git clean -fx

      - name: Create tag message
        run: echo `git tag -n10 -l $(git describe --abbrev=0 --tags) | sed 's/^[0-9.]*[ ]*//g'` >> TAG_MESSAGE

      - name: Build extension files
        run: composer extension-release

      - name: Publish to TER
        run: /home/runner/.composer/vendor/bin/ter-client upload t3visuellverstehen . -u "${{ secrets.TYPO3_ORG_USERNAME }}" -p "${{ secrets.TYPO3_ORG_PASSWORD }}" -m "$(cat TAG_MESSAGE)"
